name: notasbex
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  flutter_speed_dial: ^7.0.0
  get_it: ^7.7.0
  path_provider: ^2.1.4
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
